Разметка главной страницы и каталога
htmlacademy-htmlcss/1868975-device-36 pull request #3
Opened 2023-01-21 21:06 UTC by Exce11o

2023-01-24 08:30 UTC, vadimrahmanov requested changes
- Если изменения касаются шапки/подвала не забудь внести правки на всех страницах.

2023-01-24 08:30 UTC, vadimrahmanov commented on catalog.html
> +                <input type="checkbox" id="red"" name="red">
Опечатка (дополнительные кавычки после red)

2023-01-24 08:30 UTC, vadimrahmanov commented on catalog.html
> +        <form class="main-search-form" action="https://echo.htmlacademy.ru/courses" method="get">
Для тестирования правильности работы форм нужно использовать адрес https://echo.htmlacademy.ru/.

2023-01-24 08:30 UTC, vadimrahmanov commented on index.html
> +        <form class="main-search-form" action="https://echo.htmlacademy.ru/courses" method="get">
Тоже самое замечание, что и в каталоге.

2023-01-24 08:30 UTC, vadimrahmanov commented on index.html
> +              <b class="slider-pagination-title">Делай селфи,<br>как Бен Стиллер!</b>
`<b>` устаревший тэг. Используй `<strong>`

2023-01-24 08:30 UTC, vadimrahmanov commented on index.html
> +          </button>
Опечатка - после prev и next пробел.

2023-01-24 08:30 UTC, vadimrahmanov commented on index.html
> +        <form action="https://echo.htmlacademy.ru/courses">
Для тестирования правильности работы форм нужно использовать адрес https://echo.htmlacademy.ru/.

Также не указан метод.

2023-01-24 08:30 UTC, vadimrahmanov commented on index.html
> +          <a class="footer-social-link" href="https://twitter.com/htmlacademy_ru">
Используй уж тогда все названия на английском, чтобы было констистентно.

2023-01-24 08:30 UTC, vadimrahmanov commented on index.html
> +              <b class="slider-pagination-title">Порхает как бабочка,<br>жалит как пчела!</b>
`<b>` устаревший тэг. Используй `<strong>`

2023-01-24 08:30 UTC, vadimrahmanov commented on index.html
> +              <div class=" subcatalog-hide">
Опечатка - пробел перед названием класса.

2023-01-24 08:30 UTC, vadimrahmanov commented on index.html
> +              <a class="subcatalog-button" href="#">Каталог товаров</a>
Раз страница уже есть, можно на неё и ссылку вставить.

2023-01-24 08:30 UTC, vadimrahmanov commented on catalog.html
> +      <h1 class="visually-hidden">Интернет-магазин гаджетов "DEVICE"</h1>
У главной страницы и каталога не должно быть одинаковых заголовков.

2023-01-24 19:03 UTC, Exce11o commented on index.html
> +              <a class="subcatalog-button" href="#">Каталог товаров</a>
При клике по слову каталог должна открываться страница каталога? Я думал, что при этом открывается выпадающее меню, а уж при клике по категории уводит в каталог. Только при нажатии на + выпадет меню?

2023-01-24 19:05 UTC, Exce11o commented on index.html
> +              <b class="slider-pagination-title">Порхает как бабочка,<br>жалит как пчела!</b>
Ещё в каталоге цены обёрнуты тегом <b>. Там тоже поменять?

2023-01-24 20:41 UTC, vadimrahmanov commented on index.html
> +              <b class="slider-pagination-title">Порхает как бабочка,<br>жалит как пчела!</b>
Везде.

2023-01-24 21:00 UTC, vadimrahmanov commented on index.html
> +              <a class="subcatalog-button" href="#">Каталог товаров</a>
В принципе такой сценарий будет лучше, так как нету ТЗ, а страница Каталога у тебя не совсем Каталог, а "Монопопады для селфи". То есть ссылка должна быть на вторую страницу на "Монопады для селфи".

2023-01-25 07:40 UTC, vadimrahmanov approved these changes

2023-01-25 07:42 UTC, merged